# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
latex: false

env:
  - _R_CHECK_FORCE_SUGGESTS_=false
 global: RGL_USE_NULL=TRUE

after_success:
  - Rscript -e 'covr::codecov()'

before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
deploy:
  provider: script
  script:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))' ; fi
  skip_cleanup: true



matrix:
  include:
    - dist: trusty
    - dist: xenial
      r_check_args: '' # because _R_CHECK_THINGS_IN_TEMP_DIR_ is broken
    - os: osx
      brew_packages: imagemagick
      osx_image:  xcode11.3
    - dist: trusty
      addons:
        apt:
          update: true
          packages:
            - libmagick++-dev
            - librsvg2-dev
            - libwebp-dev
            - libpoppler-cpp-dev
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            - r-cran-rgdal
            - libfftw3-dev
            - cargo
            - gsfonts
            - libgdal-dev
            - libproj-dev

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:cran/imagemagick'
    packages:
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - libfftw3-dev
      - cargo
      - gsfonts
      - libgdal-dev
      - libproj-dev

bioc_packages: EBImage
